FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.api.txt requirements.ml.txt requirements.dev.txt ./
RUN pip install --no-cache-dir --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.ml.txt -r requirements.dev.txt
RUN python -m spacy download en_core_web_sm

COPY . .

CMD ["python", "-m", "worker.transcriber"]
