import { fireEvent, render, screen } from '@testing-library/react'
import { configureStore } from '@reduxjs/toolkit'
import { Provider } from 'react-redux'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import eventsReducer, { viewportEventsSet } from '../store/eventsSlice'
import uiReducer from '../store/uiSlice'
import type { SafetyEvent } from '../../../../shared/types'
import { LiveMapPage } from './LiveMapPage'

const { breakpoint, currentLocation, router, loadHome } = vi.hoisted(() => ({ breakpoint: { layout: 'desktop' as 'desktop' | 'mobile' }, currentLocation: { location: null as null | { lat: number; lng: number; accuracy: number }, status: 'idle', error: null as Error | null, startFollowing: vi.fn(), stopFollowing: vi.fn(), disable: vi.fn() }, router: { params: new URLSearchParams(), setParams: vi.fn() }, loadHome: vi.fn().mockResolvedValue(null) }))
vi.mock('../hooks/useBreakpoint', () => ({ useBreakpoint: () => breakpoint }))
vi.mock('../hooks/useViewportWs', () => ({ useViewportWs: vi.fn() }))
vi.mock('../hooks/useCurrentLocation', () => ({ useCurrentLocation: () => currentLocation }))
vi.mock('../components/map/MapCanvas', () => ({ MapCanvas: ({ children, cameraCommand, onUserInteraction, onBoundsChange }: { children: React.ReactNode; cameraCommand?: unknown; onUserInteraction?: () => void; onBoundsChange?: (bounds: { north: number; south: number; east: number; west: number }, zoom: number) => void }) => <div data-testid="map-canvas" data-camera={cameraCommand ? JSON.stringify(cameraCommand) : ''}>{children}<button onClick={onUserInteraction}>move map</button><button onClick={() => onBoundsChange?.({ north: 1.238, south: 1.232, east: 36.828, west: 36.822 }, 12)}>report bounds</button></div> }))
vi.mock('../components/map/MapSearch', () => ({ MapSearch: ({ initialQuery }: { initialQuery: string }) => <div data-testid="map-search">{initialQuery}</div> }))
vi.mock('../components/map/EventClusterLayer', () => ({ EventClusterLayer: ({ events, onEventClick, onClusterClick }: { events: SafetyEvent[]; onEventClick: (event: SafetyEvent) => void; onClusterClick: (events: SafetyEvent[]) => void }) => <div data-testid="event-layer">{events.map(e => e.title).join(',')}<button onClick={() => onEventClick(events[0])}>select marker</button><button onClick={() => onClusterClick(events)}>expand cluster</button></div> }))
vi.mock('../components/map/RadiusZoneLayer', () => ({ RadiusZoneLayer: () => <div data-testid="radius-layer" /> }))
vi.mock('../components/map/HomeLocationMarker', () => ({ HomeLocationMarker: ({ home }: { home: { label: string } }) => <div data-testid="home-marker">{home.label}</div> }))
vi.mock('../components/map/LocationMarker', () => ({ LocationMarker: () => <div data-testid="location-marker" /> }))
vi.mock('../components/HomeRoutePanel', () => ({ HomeRoutePanel: ({ searchProximity, onRoutePreview }: { searchProximity?: { lat: number; lng: number }; onRoutePreview?: (routes: unknown[], index: number) => void }) => <div data-testid="home-panel" data-proximity={searchProximity ? JSON.stringify(searchProximity) : ''}><button onClick={() => onRoutePreview?.([{ id: 'same', coordinates: [[2, 1]], distanceKm: 0, durationMin: 0, warnings: [], label: 'Same', mode: 'walking', alertIntersections: 0 }], 0)}>fit route</button></div> }))
vi.mock('../services/homeLocationStore', () => ({ loadHomeLocation: loadHome }))
vi.mock('react-router-dom', () => ({ useNavigate: () => vi.fn(), useSearchParams: () => [router.params, router.setParams] }))

const event: SafetyEvent = { id: 'e1', event_type: 'SECURITY_INCIDENT', severity: 'HIGH', title: 'Market alert', summary: null, lat: -1.28, lng: 36.82, place_name: 'Market', county: null, is_active: true, state: 'ACTIVE', started_at: '2026-01-01T00:00:00Z', created_at: '2026-01-01T00:00:00Z', nostr_event_id: null, trust_state: 'confirmed' }
function renderPage() { const store = configureStore({ reducer: { events: eventsReducer, ui: uiReducer } }); store.dispatch(viewportEventsSet([event])); return render(<Provider store={store}><LiveMapPage /></Provider>) }

beforeEach(() => { breakpoint.layout = 'desktop'; currentLocation.location = null; currentLocation.status = 'idle'; currentLocation.error = null; currentLocation.startFollowing.mockClear(); currentLocation.stopFollowing.mockClear(); currentLocation.disable.mockClear(); loadHome.mockReset().mockResolvedValue(null); router.params = new URLSearchParams(); router.setParams.mockClear() })
describe('LiveMapPage field atlas', () => {
  it('renders viewport instruments and desktop field ledger', () => { renderPage(); expect(screen.getByLabelText('Viewport status')).toBeInTheDocument(); expect(screen.getByText('Incidents in view')).toBeInTheDocument() })
  it('renders a collapsed field ledger on mobile', () => { breakpoint.layout = 'mobile'; renderPage(); expect(screen.getByRole('button', { name: /1 in view/i })).toHaveAttribute('aria-expanded', 'false') })
  it('filters both map events and the ledger', () => { renderPage(); fireEvent.click(screen.getByRole('button', { name: 'Traffic' })); expect(screen.getByTestId('event-layer')).not.toHaveTextContent('Market alert'); expect(screen.getByText('Quiet viewport')).toBeInTheDocument() })
  it('toggles approximate impact zones', () => { renderPage(); fireEvent.click(screen.getByTitle('Toggle impact zones')); expect(screen.queryByTestId('radius-layer')).not.toBeInTheDocument() })
  it('explains that location is optional', () => { currentLocation.error = new Error('denied'); renderPage(); expect(screen.getByText(/Location is optional/)).toBeInTheDocument() })
  it('focuses marker and ledger selections by current event ID', () => { renderPage(); fireEvent.click(screen.getByRole('button', { name: 'select marker' })); expect(JSON.parse(screen.getByTestId('map-canvas').dataset.camera!)).toMatchObject({ center: [36.82, -1.28], zoom: 15 }); expect(screen.getByRole('heading', { name: 'Market alert' })).toBeInTheDocument() })
  it('fits all cluster members without selecting an event', () => { renderPage(); fireEvent.click(screen.getByRole('button', { name: 'expand cluster' })); expect(JSON.parse(screen.getByTestId('map-canvas').dataset.camera!)).toMatchObject({ bounds: [36.819, -1.281, 36.821, -1.2790000000000001] }); expect(screen.getByText('Incidents in view')).toBeInTheDocument() })
  it('consumes q once and automatically seeds map search', () => { router.params = new URLSearchParams('q=Central+Park'); renderPage(); expect(screen.getByTestId('map-search')).toHaveTextContent('Central Park'); expect(router.setParams).toHaveBeenCalledWith(new URLSearchParams(), { replace: true }) })
  it('preserves and announces an unavailable event deep link', () => { router.params = new URLSearchParams('event=missing'); renderPage(); expect(screen.getByRole('status')).toHaveTextContent('not currently available'); expect(router.setParams).not.toHaveBeenCalled() })
  it('resolves and focuses a loaded event deep link', () => { router.params = new URLSearchParams('event=e1'); renderPage(); expect(JSON.parse(screen.getByTestId('map-canvas').dataset.camera!)).toMatchObject({ center: [36.82, -1.28] }); expect(screen.getByRole('heading', { name: 'Market alert' })).toBeInTheDocument() })
  it('activates GPS only from the location control and pauses follow on user map movement', () => { renderPage(); expect(currentLocation.startFollowing).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: 'Enable current location' })); expect(currentLocation.startFollowing).toHaveBeenCalledOnce(); fireEvent.click(screen.getByRole('button', { name: 'move map' })); expect(currentLocation.stopFollowing).toHaveBeenCalledOnce() })
  it('hydrates encrypted home without blocking the map render', async () => { loadHome.mockResolvedValue({ lat: 1, lng: 2, label: 'Device home' }); renderPage(); expect(screen.getByTestId('map-canvas')).toBeInTheDocument(); expect(await screen.findByTestId('home-marker')).toHaveTextContent('Device home') })
  it('passes only rounded visible map center to home search', () => { currentLocation.location = { lat: 1.234567, lng: 36.823456, accuracy: 4 }; renderPage(); fireEvent.click(screen.getByRole('button', { name: 'report bounds' })); fireEvent.click(screen.getByRole('button', { name: 'Set home and preview route' })); expect(JSON.parse(screen.getByTestId('home-panel').dataset.proximity!)).toEqual({ lat: 1.23, lng: 36.83 }); expect(screen.getByTestId('home-panel').dataset.proximity).not.toContain('1.234567') })
  it('expands degenerate route preview bounds', async () => { currentLocation.location = { lat: 1, lng: 2, accuracy: 4 }; loadHome.mockResolvedValue({ lat: 1, lng: 2, label: 'Same place' }); renderPage(); await screen.findByTestId('home-marker'); fireEvent.click(screen.getByRole('button', { name: 'Set home and preview route' })); fireEvent.click(screen.getByRole('button', { name: 'fit route' })); expect(JSON.parse(screen.getByTestId('map-canvas').dataset.camera!)).toMatchObject({ bounds: [1.999, 0.999, 2.001, 1.001] }) })
})
